/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Partida;
import modelo.Usuario;

/**
 *
 * @author luisd
 */
public class vistaEscribirPalabra extends javax.swing.JFrame {

    /**
     * Creates new form vistaDibujante
     */
    public Partida partida = new Partida();
    JFrame f;
    public Usuario usuarioActual = new Usuario();

    public vistaEscribirPalabra() {
        initComponents();
        this.getContentPane().setBackground(new Color(80, 207, 164));
        setFocusableWindowState(true);
        this.setLocationRelativeTo(null);
        hiloTiempo.start();
        partida.conexionServidor();
    }

    Thread hiloTiempo = new Thread() {
        @Override
        public void run() {
            for (int i = 0; i <= Partida.tiempoPartida; i++) {
                try {
                    Thread.sleep(1000);
                    barraDeTiempo.setValue(i);
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                }
            }
            JOptionPane.showMessageDialog(
                    f,
                    "¡TIEMPO!");
            itsDone();
        }
    };

    private void itsDone() {
        partida.primeraPalabra(Usuario.region, Usuario.idEnPartida, fieldAdivinar.getText());
        jlabelTextoAdvinar.setVisible(false);
        fieldAdivinar.setVisible(false);
        barraDeTiempo.setVisible(false);
        botonAdivinar.setVisible(false);
        vistaSketch sketch = new vistaSketch();
        sketch.setVisible(true);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        barraDeTiempo = new javax.swing.JProgressBar();
        jlabelTextoAdvinar = new javax.swing.JLabel();
        botonAdivinar = new javax.swing.JButton();
        fieldAdivinar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escribe una palabra");
        setBackground(new java.awt.Color(80, 207, 164));
        setFocusableWindowState(false);
        setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 800));

        jLabelLogo.setBackground(new java.awt.Color(0, 216, 198));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSketchAndGuessSmall.png"))); // NOI18N

        barraDeTiempo.setBackground(new java.awt.Color(204, 255, 255));
        barraDeTiempo.setMaximum(60);

        jlabelTextoAdvinar.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jlabelTextoAdvinar.setForeground(new java.awt.Color(255, 255, 255));
        jlabelTextoAdvinar.setText("Escribe una palabra para que los demás dibujen");

        botonAdivinar.setBackground(new java.awt.Color(0, 192, 126));
        botonAdivinar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        botonAdivinar.setForeground(new java.awt.Color(255, 255, 255));
        botonAdivinar.setText("¡LISTO!");
        botonAdivinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdivinarActionPerformed(evt);
            }
        });

        fieldAdivinar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        fieldAdivinar.setText("Escribe aquí...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jlabelTextoAdvinar)
                .addGap(0, 246, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(fieldAdivinar, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(barraDeTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(547, 547, 547)
                        .addComponent(botonAdivinar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jlabelTextoAdvinar)
                .addGap(87, 87, 87)
                .addComponent(fieldAdivinar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(barraDeTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(botonAdivinar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAdivinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdivinarActionPerformed
        // TODO add your handling code here:
        hiloTiempo.stop();
        JOptionPane.showMessageDialog(
                f,
                "Genial!, ahora solo queda esperar a los demás");
        itsDone();
    }//GEN-LAST:event_botonAdivinarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaEscribirPalabra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaEscribirPalabra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaEscribirPalabra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaEscribirPalabra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaEscribirPalabra().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraDeTiempo;
    private javax.swing.JButton botonAdivinar;
    private javax.swing.JTextField fieldAdivinar;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jlabelTextoAdvinar;
    // End of variables declaration//GEN-END:variables
}
