/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Partida;
import modelo.Usuario;

/**
 *
 * @author luisd
 */
public class vistaSalaEspera extends javax.swing.JFrame {

    /**
     * Creates new form vistaDibujante
     */
    public Partida partida = new Partida();
    JFrame f;
    public Usuario usuarioActual = new Usuario();
    private int partidaHasStarted = 0;
    private String[] usuariosTodos = new String[6];

    public vistaSalaEspera() {
        initComponents();
        this.getContentPane().setBackground(new Color(142, 148, 236));
        setFocusableWindowState(true);
        this.setLocationRelativeTo(null);
        partida.conexionServidor();
        botonEmpezar.setVisible(false);
        jLabelEspera.setVisible(false);
        lblActualizar.setVisible(false);
        jLabelUsuarioActual.setText(usuarioActual.getNombreUsuario());
        jLabelPuntajeMaximo.setText(String.valueOf(usuarioActual.getPuntajeMaximo()));
        obtenerDatosInicial();
    }

    private void obtenerDatosInicial() {

        jLabelUsuario2.setText(null);
        jLabelUsuario3.setText(null);
        jLabelUsuario4.setText(null);
        jLabelUsuario5.setText(null);
        usuariosTodos[0] = null;
        usuariosTodos[1] = null;
        usuariosTodos[2] = null;
        usuariosTodos[3] = null;
        usuariosTodos[4] = null;
        usuariosTodos[5] = null;
    }

    private void actualizarDatoslbl() {
        usuariosTodos = partida.obtenerUsuarios(Usuario.region);
        if (usuariosTodos[4] != null && usuariosTodos[5] == null) {//Ya están todos los usuarios, pero aún no empieza la partida
            partidaHasStarted = 2;
        } else if (usuariosTodos[5] != null) { //La partida ya empezó
            partidaHasStarted = 1;
            jLabelEspera.setText("¡Buena suerte!");
            vistaEscribirPalabra vistaPalabra = new vistaEscribirPalabra();
            this.setVisible(false);
            vistaPalabra.setVisible(true);
        } else {
            switch (Usuario.idEnPartida) {
                case 0:
                    jLabelUsuario2.setText(usuariosTodos[1]);
                    jLabelUsuario3.setText(usuariosTodos[2]);
                    jLabelUsuario4.setText(usuariosTodos[3]);
                    jLabelUsuario5.setText(usuariosTodos[4]);
                    break;
                case 1:
                    jLabelUsuario2.setText(usuariosTodos[0]);
                    jLabelUsuario3.setText(usuariosTodos[2]);
                    jLabelUsuario4.setText(usuariosTodos[3]);
                    jLabelUsuario5.setText(usuariosTodos[4]);
                    break;
                case 2:
                    jLabelUsuario2.setText(usuariosTodos[1]);
                    jLabelUsuario3.setText(usuariosTodos[0]);
                    jLabelUsuario4.setText(usuariosTodos[3]);
                    jLabelUsuario5.setText(usuariosTodos[4]);
                    break;
                case 3:
                    jLabelUsuario2.setText(usuariosTodos[1]);
                    jLabelUsuario3.setText(usuariosTodos[2]);
                    jLabelUsuario4.setText(usuariosTodos[0]);
                    jLabelUsuario5.setText(usuariosTodos[4]);
                    break;
                case 4:
                    jLabelUsuario2.setText(usuariosTodos[1]);
                    jLabelUsuario3.setText(usuariosTodos[2]);
                    jLabelUsuario4.setText(usuariosTodos[3]);
                    jLabelUsuario5.setText(usuariosTodos[0]);
                    break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelUsuarioActual = new javax.swing.JLabel();
        jLabelUsuario2 = new javax.swing.JLabel();
        jLabelEspera = new javax.swing.JLabel();
        jLabelUsuario3 = new javax.swing.JLabel();
        jLabelUsuario4 = new javax.swing.JLabel();
        jLabenPuntajeTexto = new javax.swing.JLabel();
        jLabelPuntajeMaximo = new javax.swing.JLabel();
        botonListo = new javax.swing.JButton();
        botonEmpezar = new javax.swing.JButton();
        jLabelUsuario5 = new javax.swing.JLabel();
        lblActualizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sala de Espera");
        setBackground(new java.awt.Color(142, 148, 236));
        setFocusableWindowState(false);
        setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setPreferredSize(new java.awt.Dimension(1280, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setBackground(new java.awt.Color(0, 216, 198));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSketchAndGuessSmall.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 0, -1, 118));

        jLabelUsuarioActual.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabelUsuarioActual.setForeground(new java.awt.Color(0, 216, 198));
        jLabelUsuarioActual.setText("Usuario actual");
        getContentPane().add(jLabelUsuarioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLabelUsuario2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelUsuario2.setForeground(new java.awt.Color(51, 237, 222));
        jLabelUsuario2.setText("Usuario 2");
        getContentPane().add(jLabelUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        jLabelEspera.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabelEspera.setForeground(new java.awt.Color(204, 255, 255));
        jLabelEspera.setText("Espera a los demás jugadores");
        getContentPane().add(jLabelEspera, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 660, -1, -1));

        jLabelUsuario3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelUsuario3.setForeground(new java.awt.Color(44, 216, 157));
        jLabelUsuario3.setText("Usuario 3");
        getContentPane().add(jLabelUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        jLabelUsuario4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelUsuario4.setForeground(new java.awt.Color(44, 216, 157));
        jLabelUsuario4.setText("Usuario 4");
        getContentPane().add(jLabelUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        jLabenPuntajeTexto.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabenPuntajeTexto.setForeground(new java.awt.Color(255, 255, 255));
        jLabenPuntajeTexto.setText("Tu puntaje máximo:");
        getContentPane().add(jLabenPuntajeTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 670, -1, -1));

        jLabelPuntajeMaximo.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelPuntajeMaximo.setForeground(new java.awt.Color(29, 144, 105));
        jLabelPuntajeMaximo.setText("12");
        getContentPane().add(jLabelPuntajeMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 660, 97, 56));

        botonListo.setBackground(new java.awt.Color(0, 192, 126));
        botonListo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        botonListo.setForeground(new java.awt.Color(255, 255, 255));
        botonListo.setText("¡Estoy listo!");
        botonListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListoActionPerformed(evt);
            }
        });
        getContentPane().add(botonListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 193, 56));

        botonEmpezar.setBackground(new java.awt.Color(0, 192, 126));
        botonEmpezar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        botonEmpezar.setForeground(new java.awt.Color(255, 255, 255));
        botonEmpezar.setText("Empezar");
        botonEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpezarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 193, 56));

        jLabelUsuario5.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelUsuario5.setForeground(new java.awt.Color(51, 237, 222));
        jLabelUsuario5.setText("Usuario 5");
        getContentPane().add(jLabelUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, -1, -1));

        lblActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        lblActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarMouseClicked(evt);
            }
        });
        getContentPane().add(lblActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListoActionPerformed
        // TODO add your handling code here:
        Usuario.idEnPartida = partida.usuarioListo(Usuario.region, Usuario.nombreUsuario, Usuario.puntajeMaximo);
        if (Usuario.idEnPartida == 100) {
            System.out.println("Error");
        } else if (Usuario.idEnPartida == 9) {
            JOptionPane.showMessageDialog(
                    f,
                    "La partida ya empezó");
        } else {
            if (Usuario.idEnPartida == 0) { //Es el primer usuario en entrar
                //PRIMERO
                botonListo.setVisible(false);
                botonEmpezar.setVisible(true);
                lblActualizar.setVisible(true);
            } else { //Es otro usuario
                //OTRO
                botonListo.setVisible(false);
                jLabelEspera.setVisible(true);
                lblActualizar.setVisible(true);
            }
            actualizarDatoslbl();
        }
    }//GEN-LAST:event_botonListoActionPerformed

    private void botonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpezarActionPerformed
        // TODO add your handling code here:
        usuariosTodos = partida.obtenerUsuarios(Usuario.region);
        if (usuariosTodos[1] != null) { //Valida que haya al menos dos usuarios
            partida.empiezanPartida(Usuario.region);
            this.setVisible(false);
            vistaEscribirPalabra vistaPalabra = new vistaEscribirPalabra();
            vistaPalabra.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(
                    f,
                    "Recuerda que deben ser al menos dos jugadores");
        }

    }//GEN-LAST:event_botonEmpezarActionPerformed

    private void lblActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseClicked
        // TODO add your handling code here:
        actualizarDatoslbl();
    }//GEN-LAST:event_lblActualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaSalaEspera.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaSalaEspera.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaSalaEspera.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaSalaEspera.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaSalaEspera().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEmpezar;
    private javax.swing.JButton botonListo;
    private javax.swing.JLabel jLabelEspera;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPuntajeMaximo;
    private javax.swing.JLabel jLabelUsuario2;
    private javax.swing.JLabel jLabelUsuario3;
    private javax.swing.JLabel jLabelUsuario4;
    private javax.swing.JLabel jLabelUsuario5;
    private javax.swing.JLabel jLabelUsuarioActual;
    private javax.swing.JLabel jLabenPuntajeTexto;
    private javax.swing.JLabel lblActualizar;
    // End of variables declaration//GEN-END:variables
}
