/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Dibujo;
import modelo.Partida;
import modelo.Usuario;

/**
 *
 * @author luisd
 */
public class vistaSketch extends javax.swing.JFrame {

    /**
     * Creates new form vistaDibujante
     */
    Dibujo canvas1;
    private BufferedImage image;
    public Partida partida = new Partida();
    JFrame f;
    public Usuario usuarioActual = new Usuario();
    private int colorEspera = 1;
    private ImageIcon icono;

    public vistaSketch() {
        initComponents();
        this.getContentPane().setBackground(new Color(18, 151, 140));
        setFocusableWindowState(true);
        this.setLocationRelativeTo(null);
        jButton1.setVisible(false);
        botonColor.setVisible(false);
        botonBorrar.setVisible(false);
        botonTerminarDibujo.setVisible(false);
        jlabelPalabraADibujar.setVisible(false);
        barraDeTiempo.setVisible(false);
        jlblUndo.setVisible(false);
        jlblRedo.setVisible(false);
        partida.conexionServidor();
        jlabelNombre.setText(Usuario.nombreUsuario);
//mostrarCanvas();
    }

    Thread hiloTiempo = new Thread() {
        @Override
        public void run() {
            for (int i = 0; i <= Partida.tiempoPartida; i++) {
                try {
                    Thread.sleep(1000);
                    barraDeTiempo.setValue(i);
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                }
            }
            JOptionPane.showMessageDialog(
                    f,
                    "¡TIEMPO!");
            itsDone();
        }
    };

    private void ajustarImagen() {
        try {
            int w = canvas1.getWidth();
            int h = canvas1.getHeight();
            int type = BufferedImage.TYPE_INT_BGR;
            image = new BufferedImage(w, h, type);
            Graphics2D g2 = image.createGraphics();
            canvas1.paint(g2);
            BufferedImage foto = image;
            icono = new ImageIcon(foto);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }

    private void itsDone() {
        ajustarImagen();
        partida.enviarImagen(icono, Usuario.region, Usuario.idEnPartida, 4);
        JOptionPane.showMessageDialog(
                f,
                "¡Es hora de adivinar!");
        vistaGuess guess = new vistaGuess();
        guess.setVisible(true);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        barraDeTiempo = new javax.swing.JProgressBar();
        jlabelPalabraADibujar = new javax.swing.JLabel();
        botonTerminarDibujo = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonColor = new javax.swing.JButton();
        jlblRedo = new javax.swing.JLabel();
        jlblUndo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblActualizar = new javax.swing.JLabel();
        lblEspera = new javax.swing.JLabel();
        jlabelNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sketch");
        setBackground(new java.awt.Color(4, 134, 90));
        setFocusableWindowState(false);
        setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 800));

        jLabelLogo.setBackground(new java.awt.Color(0, 216, 198));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSketchAndGuessSmall.png"))); // NOI18N

        barraDeTiempo.setBackground(new java.awt.Color(204, 255, 255));

        jlabelPalabraADibujar.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jlabelPalabraADibujar.setForeground(new java.awt.Color(255, 255, 255));
        jlabelPalabraADibujar.setText("PALABRA");

        botonTerminarDibujo.setBackground(new java.awt.Color(0, 192, 126));
        botonTerminarDibujo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        botonTerminarDibujo.setForeground(new java.awt.Color(255, 255, 255));
        botonTerminarDibujo.setText("¡LISTO!");
        botonTerminarDibujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarDibujoActionPerformed(evt);
            }
        });

        botonBorrar.setBackground(new java.awt.Color(87, 16, 215));
        botonBorrar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        botonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        botonBorrar.setText("Borrar todo");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonColor.setBackground(new java.awt.Color(51, 208, 255));
        botonColor.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        botonColor.setForeground(new java.awt.Color(255, 255, 255));
        botonColor.setText("Color");
        botonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColorActionPerformed(evt);
            }
        });

        jlblRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/redo.png"))); // NOI18N
        jlblRedo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblRedoMouseClicked(evt);
            }
        });

        jlblUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unro.png"))); // NOI18N
        jlblUndo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblUndoMouseClicked(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        lblActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarMouseClicked(evt);
            }
        });

        lblEspera.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblEspera.setForeground(new java.awt.Color(255, 255, 255));
        lblEspera.setText("Espera a los demás jugadores");

        jlabelNombre.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jlabelNombre.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(botonColor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(barraDeTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jlabelPalabraADibujar)
                        .addGap(374, 374, 374)
                        .addComponent(botonTerminarDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jlblUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblRedo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jlabelNombre)
                        .addGap(66, 66, 66))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEspera)
                .addGap(65, 65, 65)
                .addComponent(lblActualizar)
                .addGap(324, 324, 324))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonColor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBorrar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlblUndo)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jlblRedo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jlabelNombre)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lblActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(lblEspera)))
                .addGap(312, 312, 312)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraDeTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonTerminarDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlabelPalabraADibujar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarCanvas() {
        lblEspera.setVisible(false);
        lblActualizar.setVisible(false);
        botonColor.setVisible(true);
        botonBorrar.setVisible(true);
        botonTerminarDibujo.setVisible(true);
        jlabelPalabraADibujar.setVisible(true);
        barraDeTiempo.setVisible(true);
        jlblUndo.setVisible(true);
        jlblRedo.setVisible(true);
        canvas1 = new Dibujo();
        canvas1.setBounds(43, 150, 1170, 466);
        canvas1.addMouseMotionListener(new java.awt.event.MouseMotionListener() {
            @Override
            public void mouseDragged(MouseEvent e) {
                canvas1.mouseDragged(e);
            }

            @Override
            public void mouseMoved(MouseEvent e) {

            }
        });
        canvas1.addMouseListener(new java.awt.event.MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {

            }

            @Override
            public void mousePressed(MouseEvent e) {
                canvas1.mousePressed(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                canvas1.mouseReleased(e);
            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });
        this.add(canvas1);
        canvas1.m_alzada = true;
    }

    private void botonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColorActionPerformed
        // TODO add your handling code here:
        canvas1.changeColor(JColorChooser.showDialog(this, "Selecciona un color", canvas1.color));
    }//GEN-LAST:event_botonColorActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        // TODO add your handling code here:
        canvas1.erase();
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void jlblUndoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblUndoMouseClicked
        // TODO add your handling code here:
        canvas1.undo();
    }//GEN-LAST:event_jlblUndoMouseClicked

    private void jlblRedoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblRedoMouseClicked
        // TODO add your handling code here:
        canvas1.redo();
    }//GEN-LAST:event_jlblRedoMouseClicked

    private void botonTerminarDibujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarDibujoActionPerformed
        // TODO add your handling code here:
        hiloTiempo.stop();
        itsDone();
    }//GEN-LAST:event_botonTerminarDibujoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            BufferedImage foto = image;
            ImageIcon icono = new ImageIcon(foto);
            canvas1.setImg(icono.getImage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseClicked
        // TODO add your handling code here:
        switch (Usuario.validadorAccion) {
            case 0: //Es la primera palabra
                if (partida.verificarPalabrasCompletas(Usuario.region) == 1) { //Si retornó 1, quiere decir que ya están todos los usuarios (se valida que todos hayan escrito palabra) 
                    jlabelPalabraADibujar.setText(partida.palabraADibujar(Usuario.region, Usuario.idEnPartida));
                    Usuario.validadorAccion = 1; //Lo siguiente que hará, será recibir una imagen
                    mostrarCanvas();
                    hiloTiempo.start();
                } else {
                    if (colorEspera == 1) {
                        lblEspera.setForeground(new Color(255, 255, 188));
                        colorEspera = 0;
                    } else {
                        lblEspera.setForeground(Color.white);
                        colorEspera = 1;
                    }
                }
                break;
            case 2: //Recibe una palabra que no es la primera (Se valida que todos hayan enviado imagen)
                if (partida.verificarPalabrasCompletas(Usuario.region) == 1) { //Si retornó 1, quiere decir que ya están todos los usuarios (se valida que todos hayan escrito palabra) 
                    jlabelPalabraADibujar.setText(partida.palabraADibujar(Usuario.region, Usuario.idEnPartida));
                    Usuario.validadorAccion = 1; //Lo siguiente que hará, será recibir una imagen
                    mostrarCanvas();
                    hiloTiempo.start();
                } else {
                    if (colorEspera == 1) {
                        lblEspera.setForeground(new Color(255, 255, 188));
                        colorEspera = 0;
                    } else {
                        lblEspera.setForeground(Color.white);
                        colorEspera = 1;
                    }
                }
                break;
        }

    }//GEN-LAST:event_lblActualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaSketch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaSketch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaSketch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaSketch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaSketch().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraDeTiempo;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonColor;
    private javax.swing.JButton botonTerminarDibujo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jlabelNombre;
    private javax.swing.JLabel jlabelPalabraADibujar;
    private javax.swing.JLabel jlblRedo;
    private javax.swing.JLabel jlblUndo;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblEspera;
    // End of variables declaration//GEN-END:variables
}
