/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Partida;
import modelo.Usuario;

/**
 *
 * @author luisd
 */
public class vistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form vistaDibujante
     */
    public Partida partida = new Partida();
    public int acceso = 1;
    public Usuario usuarioActual = new Usuario();
    JFrame f;

    
    
    public vistaLogin() {
        initComponents();
        this.getContentPane().setBackground(new Color(220, 255, 252));
        setFocusableWindowState(true);
        this.setLocationRelativeTo(null);
        partida.conexionServidor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelClave = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jPasswordClave = new javax.swing.JPasswordField();
        jlabelTextoRegistro1 = new javax.swing.JLabel();
        jlabelTextoRegistro2 = new javax.swing.JLabel();
        jLabelRegion = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(220, 255, 252));
        setFocusableWindowState(false);
        setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 800));

        jLabelLogo.setBackground(new java.awt.Color(0, 216, 198));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSketchAndGuessSmall.png"))); // NOI18N

        botonIngresar.setBackground(new java.awt.Color(0, 192, 126));
        botonIngresar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        jLabelUsuario.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(38, 51, 226));
        jLabelUsuario.setText("Usuario");

        jLabelClave.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelClave.setForeground(new java.awt.Color(87, 98, 241));
        jLabelClave.setText("Clave");

        jTextUsuario.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        jPasswordClave.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        jlabelTextoRegistro1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlabelTextoRegistro1.setForeground(new java.awt.Color(44, 216, 157));
        jlabelTextoRegistro1.setText("¿No tienes un usuario?");

        jlabelTextoRegistro2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jlabelTextoRegistro2.setForeground(new java.awt.Color(20, 145, 102));
        jlabelTextoRegistro2.setText("¡Regístrate acá!");
        jlabelTextoRegistro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelTextoRegistro2MouseClicked(evt);
            }
        });

        jLabelRegion.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabelRegion.setForeground(new java.awt.Color(38, 51, 226));
        jLabelRegion.setText("Región");

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colombia", "México", "Chile" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelClave)
                    .addComponent(jLabelUsuario)
                    .addComponent(jLabelRegion))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jPasswordClave)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(460, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlabelTextoRegistro1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlabelTextoRegistro2)))
                        .addGap(389, 389, 389))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsuario))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClave)
                    .addComponent(jPasswordClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegion)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(botonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelTextoRegistro1)
                    .addComponent(jlabelTextoRegistro2))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
        try {
            String usuario = jTextUsuario.getText();
            String clave = jPasswordClave.getText();
            int region;
            if (jComboBox1.getSelectedItem().equals("Colombia")) {
                region = 1;
            } else if (jComboBox1.getSelectedItem().equals("Chile")) {
                region = 3;
            } else {
                region = 2;
            }
            acceso = partida.login(usuario, clave, region);
            switch (acceso) {
                case 0:
                    //Login satisfactorio
                    usuarioActual.setNombreUsuario(usuario);
                    usuarioActual.setRegion(region);
                    int[] datosUs = partida.datosUsuario(usuario);
                    usuarioActual.setIdUsuario(datosUs[0]);
                    usuarioActual.setTipoUsuario(datosUs[1]);
                    usuarioActual.setPuntajeMaximo(datosUs[2]);
                    if (Usuario.tipoUsuario == 0) { //El usuario es admin
                        vistaAdministrador admin = new vistaAdministrador();
                        admin.setVisible(true);
                        this.setVisible(false);
                    } else { //Es usuario común
                        vistaSalaEspera sala = new vistaSalaEspera();
                        sala.setVisible(true);
                        this.setVisible(false);
                    }
                    break;
                //Región llena
                case 2:
                    JOptionPane.showMessageDialog(f, "¡Región llena, intenta con otra!", "Error", JOptionPane.WARNING_MESSAGE);
                    break;
                default:
                    //Error en login
                    JOptionPane.showMessageDialog(f, "Usuario y/o contraseña incorrectos", "Error", JOptionPane.WARNING_MESSAGE);
                    break;
            }
        } catch (HeadlessException ex) {
            Logger.getLogger(vistaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jlabelTextoRegistro2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelTextoRegistro2MouseClicked
        // TODO add your handling code here:
        int region = 1;
        String usuario = JOptionPane.showInputDialog(
                f,
                "Digita el nombre de usuario",
                "Nuevo usuario",
                JOptionPane.QUESTION_MESSAGE);
        String clave = JOptionPane.showInputDialog(
                f,
                "Digita tu contraseña",
                "Nuevo usuario",
                JOptionPane.NO_OPTION);
        String claveConf = JOptionPane.showInputDialog(
                f,
                "Confirma tu contraseña",
                "Nuevo usuario",
                JOptionPane.NO_OPTION);
        if (clave.equals(claveConf)) {
            Object seleccion = JOptionPane.showInputDialog(
                    f,
                    "Selecciona tu región",
                    "Nuevo usuario",
                    JOptionPane.QUESTION_MESSAGE,
                    null, // null para icono defecto
                    new Object[]{"Colombia", "México", "Chile"},
                    "Colombia");
            if (seleccion.equals("Colombia")) {
                region = 1;
            } else if (seleccion.equals("Chile")) {
                region = 3;
            } else {
                region = 2;
            }
            try {
                acceso = partida.registro(usuario, clave, region);
                if (acceso == 0) { //Registro satisfactorio 
                    usuarioActual.setNombreUsuario(usuario);
                    usuarioActual.setRegion(region);
                    int[] datosUs = partida.datosUsuario(usuario);
                    usuarioActual.setIdUsuario(datosUs[0]);
                    usuarioActual.setTipoUsuario(datosUs[1]);
                    usuarioActual.setPuntajeMaximo(datosUs[2]);
                    JOptionPane.showMessageDialog(
                            f,
                            "Registro satisfactorio");
                } else {//Error en registro
                    f = new JFrame();
                    JOptionPane.showMessageDialog(f, "El usuario ya existe", "Error", JOptionPane.WARNING_MESSAGE);
                }
            } catch (HeadlessException ex) {
                Logger.getLogger(vistaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(
                    f,
                    "Las contraseñas no coinciden");
        }
    }//GEN-LAST:event_jlabelTextoRegistro2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelClave;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelRegion;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordClave;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JLabel jlabelTextoRegistro1;
    private javax.swing.JLabel jlabelTextoRegistro2;
    // End of variables declaration//GEN-END:variables
}
